#!/usr/bin/env python3
"""Generate kernel/net/webpki_roots_data.c from certs/webpki/*.der (or *.pem)."""
from pathlib import Path
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
SRC = ROOT / "certs" / "webpki"
OUT = ROOT / "kernel" / "net" / "webpki_roots_data.c"

def load_der(path: Path) -> bytes:
    if path.suffix.lower() == ".der":
        return path.read_bytes()
    pem = path.read_bytes()
    r = subprocess.run(
        ["openssl", "x509", "-inform", "PEM", "-outform", "DER"],
        input=pem, capture_output=True, check=True,
    )
    return r.stdout

def main() -> int:
    files = sorted(list(SRC.glob("*.der")) + list(SRC.glob("*.pem")))
    if not files:
        print(f"no roots in {SRC}", file=sys.stderr)
        return 1
    roots = []
    for f in files:
        der = load_der(f)
        name = "root_" + f.stem.replace("-", "_").replace(".", "_")
        roots.append((name, der))
    lines = [
        "/* Auto-generated by scripts/gen-webpki-roots.py — do not edit by hand. */\n",
        '#include "webpki.h"\n',
        '#include "types.h"\n',
    ]
    for name, der in roots:
        xs = ",".join(f"0x{b:02x}" for b in der)
        lines.append(f"static const uint8_t {name}[] = {{{xs}}};\n")
    lines.append("const struct webpki_root webpki_roots[] = {\n")
    for name, der in roots:
        lines.append(f"    {{ {name}, sizeof({name}) }},\n")
    lines.append("};\n")
    lines.append(
        "const int webpki_root_count = (int)(sizeof(webpki_roots) / sizeof(webpki_roots[0]));\n"
    )
    OUT.write_text("".join(lines))
    print(f"wrote {OUT} ({len(roots)} roots, {sum(len(d) for _, d in roots)} bytes)")
    return 0

if __name__ == "__main__":
    raise SystemExit(main())
